[tool.poetry]
name = "smpclient"
version = "0"
description = "Simple Management Protocol (SMP) Client for remotely managing MCU firmware"
authors = [
    "J.P. Hutchins <jphutchins@gmail.com>",
    "J.P. Hutchins <jp@intercreate.io"
]
readme = "README.md"
license = "Apache-2.0"
packages = [
    { include = "smpclient" },
]

[tool.poetry.scripts]
mcuimg = "smpclient.mcuboot:mcuimg"

[tool.poetry-version-plugin]
source = "git-tag"

[tool.poetry.dependencies]
python = ">=3.8.1, <3.13"
pyserial = "^3.5"
smp = "^2.0.0"
intelhex = "^2.3.0"
bleak = "^0.22.1"
async-timeout = { version = "^4.0.3", python = "<3.11" }
python-can = "^4.3.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
black = "^23.11.0"
flake8 = "^6.1.0"
isort = "^5.12.0"
mypy = "^1.7.0"
mypy-extensions = "^1.0.0"
pytest-asyncio = "^0.23.2"
types-pyserial = "^3.5.0.11"
tox = "^4.15.0"

[tool.black]
line-length = 100
skip-string-normalization = true
extend-exclude = "dutfirmware|.venv|tests/fixtures|.tox"

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
skip = [
    ".venv",
    "dutfirmware",
    ".tox",
]

[tool.mypy]
disallow_untyped_defs = true
exclude = ['.venv', 'dutfirmware', '.tox']

[tool.pytest.ini_options]
norecursedirs = "dutfirmware/*"
filterwarnings = [
    "ignore:The --rsyncdir:DeprecationWarning",
]

[tool.tox]
legacy_tox_ini = """
    [tox]
    min_version = 4.15
    env_list =
        py38
        py39
        py310
        py311
        py312

    [testenv]
    allowlist_externals =
        poetry
        black
        isort
        flake8
        mypy
        coverage
    commands = 
        poetry install
        black --check .
        isort --check-only .
        flake8 .
        mypy .
        coverage erase
        pytest --cov --maxfail=1
"""

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
